name: VolticTNT
main: net.volticmc.tntbattle.TNTBattle
description: TNT Game plugin for Voltic
author: VolticMC
version: 1.0.0
commands:
  forcestart:
    description: forces game start
    usage: /forcestart